In [1]:
import numpy as np

my_list = list(range(1000000))
my_array = np.arange(1000000)

In [4]:
%timeit my_list_by2 = [i * 2 for i in my_list]
%timeit my_array2 = my_array * 2 # 넘파이가 효율적이라서 시간이 적게 걸린다

65.6 ms ± 5.47 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.44 ms ± 293 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
a = [
    [1, 1.2, 3],
    [-123, 123, 0],
]

data = np.array(a) # 리스트를 출력을 해주는데 소숫점을 맞춰서 보기 편하게 출력해준다
print(data)

[[   1.     1.2    3. ]
 [-123.   123.     0. ]]


In [17]:
# 0차원 : 스칼라(), 1차원 : 벡터()
# 2차원 : 매트릭스(), 3차원 : 텐서()
print(data * 10) # numpy안썼으면 10번 concatenation 햇을 것이다
print(data + data)

[[   10.    12.    30.]
 [-1230.  1230.     0.]]
[[   2.     2.4    6. ]
 [-246.   246.     0. ]]


In [9]:
print(data.shape) # 모양을 찍어달라 가장 바깥에 있는 리스트가 2개 있고 그 안에 3개의 요소(혹은 또다른 리스트)
print(data.dtype) # 가장 큰 단위의 배열의 갯수

(2, 3)
float64


# ndarray 생성하기 (nd == n 차원)

In [11]:
data1 = range(1, 6)
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
arr2 = np.array([[1.1, 2.2], [3.3, 4.4]])
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [16]:
print(arr1.ndim) # 1차원(벡터)
print(arr2.ndim) # 2차원(

1
2


In [15]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 2)


In [22]:
# print([0] * 10)  0을 10번 concatetion 해줘
print(np.zeros(10)) # 데이터는 모르겠는데 구조를 먼저 만들고 싶어라고 할때ㅔ 쓴다
print(np.zeros((5, 5)))
print(np.empty((2, 2, 2))) # 빈칸 넣어서 구조를 눈으로 볼때

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [24]:
print(np.arange(10)) # 0부터 끝나는 지점을 만들어줘서.. 그담에 뭐..?

[0 1 2 3 4 5 6 7 8 9]


# ndarray 자료형

In [28]:
arr1 = np.array([1, 2, 3], dtype=np.float64) # 생성할때 속성을 넣어서 소수로 형변환 할거야
arr2 = np.array([1, 2, 3], dtype=np.int32) # 생성할때 속성을 넣어서 정수로 형변환 할거야

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [30]:
# 생성하고 나서 형변환 할때는 이렇게 한다
arr1 = np.array([1, 2, 3])
print(arr1.dtype)

float_arr1 = arr1.astype(np.float64)
print(float_arr1)
print(float_arr1.dtype)
# 소수를 정수로 바꿀수도 있다. 그럼 소수점 아래는 버림처리(파이썬 기본문법도 그러하다)

int64
[1. 2. 3.]
float64


# 산술연산

In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [35]:
print(arr * arr)
print(arr + arr)
print(1 / arr)
print(arr ** 3) # 같은 위치끼리의 산술연산하는 방식

[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [40]:
arr2 = np.array([[3, 2, 1],[1, 2, 3]])
print(arr)       # arr | 1, 2, 3 |  arr2 | 3, 2, 1 |
print(arr2)      #     | 4, 5, 6 |       | 1, 2, 3 |
print(arr > arr2) # 같은 위치끼리의 비교(이거 많이쓴다)
print(arr == 3)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[False False  True]
 [False False False]]


## 색인(인덱싱)과 슬라이싱

In [52]:
arr = np.arange(10)
print(arr)
print(type(np.arange(10)))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [53]:
arr[5]

np.int64(5)

In [54]:
arr[7]

np.int64(7)

In [55]:
arr[2:5] # 슬라이싱

array([2, 3, 4])

In [56]:
arr[2:5] = 10

In [57]:
print(arr) # 스칼라 대입을 하면 모든 위치에 데이터가 다 갈아치워진다

[ 0  1 10 10 10  5  6  7  8  9]


In [58]:
py_list = [1, 2, 3, 4, 5]
py_list[2:3].pop()
print(py_list)

[1, 2, 3, 4, 5]


In [59]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [64]:
print(arr[0])
print(arr[1])
print(arr[1][0])
print(arr[1, 0])

[1 2 3]
[4 5 6]
4
4


In [65]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],    # 이런 구조가 3차원이다
               [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
               [[11, 22, 33], [44, 55, 66], [77, 88, 99]]]
              )

In [72]:
print(arr3d[2])  # 인덱싱 개념
print(arr3d[2, 0]) # 점점 대괄호 갯수가
print(arr3d[2, 0, 1]) # 줄어든다

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[11 22 33]
22


In [78]:
# a:b라고 하면 a번째 부터 b번째 미만까지
print(arr3d[:1])
print(arr3d[:1, 1:])
print(arr3d[:1, 1:, 2:])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[4 5 6]
  [7 8 9]]]
[[[6]
  [9]]]


In [81]:
arr3d[0, 1:, 2:] # 대괄호의 갯수에 따라 인덱싱과 슬라이싱의 차이가 발생한다. 아예 배열안으로 들어가느냐(인덱싱) 그냥 잘라서 쓰느냐

array([[6],
       [9]])

## boolean 값으로 선택

In [83]:
names = np.array(['hong', 'kim', 'hong', 'kim']) # 여기서 첫번째 hong과 두번째 hong은 같은 사람이지만 배열의위치를 동일시하기 위해서 맞춰줬다는 개념
data = np.array(
    [
        ['math', 60], ['math', 90], ['eng', 70], ['eng', 50]
    ]
)

In [84]:
names == 'hong'

array([ True, False,  True, False])

In [86]:
# data[[True, False,  True, False]]
data[names =='hong']

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

- 이와 같이 특정 조건에 맞는 값을 찾을 때 쓴다

In [90]:
print(data[names =='hong', 1]) # 인덱스 접근
print(data[names =='hong', :1]) # 슬라이싱을 한 것

['60' '70']
[['math']
 ['eng']]


In [92]:
print(names != 'hong')
print(~(names == 'hong'))
# 이 두가지의 용법이 같다

[False  True False  True]
[False  True False  True]


In [93]:
# 근데 보통 이렇게 조건을 변수에 넣어서 사용한다
cond = names == 'kim'
data[cond]

array([['math', '90'],
       ['eng', '50']], dtype='<U21')

## 팬시 색인(fancy indexing)
- 조금 더 특정하는 방식

In [94]:
arr = np.zeros((8, 4)) # 8행 4열짜리를 만들겠다
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [96]:
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [97]:
arr[[4, 3, 0, 5]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [98]:
arr[[-3, -5, -1]] # 인덱스 음수접근은 맨 뒤에서 몇번째를 나타내므로 뒤에서 3번째, 뒤에서 5번째, 맨뒤에것

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [106]:
arr = np.arange(32).reshape(8, 4)
print(arr[[1, 5]])
print(arr[[1, 5], [2, 3]]) # 일렬로 값을 반환할때 이렇게 쓴다

[[ 4  5  6  7]
 [20 21 22 23]]
[ 6 23]


In [109]:
arr[[1, 5]][:, [2, 3]] # 표같은 형태로 반환된다

array([[ 6,  7],
       [22, 23]])

## 배열 전치
- 배열 축을 바꾸는 것

In [111]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [112]:
print(arr.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [113]:
arr * 3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42]])

In [115]:
arr @ arr.T # 행렬의 내적 or 행렬의 곱

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [117]:
# 위의 행렬의 내적과 같은 용법..(근데 쓸일 없다고 하셨음)
np.dot(arr, arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

## numpy 함수
- np.xxxxx

In [119]:
samples = np.random.standard_normal(size=(3, 3))
print(samples)        # 어떤 랜덤한 숫자의 3x3배열을 만든다는 뜻

[[-0.05086951 -1.72759674  1.29022981]
 [ 1.10096879 -0.55379542  0.47442663]
 [-0.51919113 -0.39620118 -0.8097372 ]]


In [123]:
arr1 = np.sqrt(samples)
print(arr1)

[[       nan        nan 1.13588283]
 [1.0492706         nan 0.68878635]
 [       nan        nan        nan]]


C:\Users\1-04\AppData\Local\Temp\ipykernel_9304\1273485535.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples)


- `nan : not a number` 음수에 루트를 씌울 수 없어서 나오는 결과였다 (결측치)

In [125]:
arr2 = np.abs(samples) # absolute 절대값2 = np.abs(samples) # absolute 절대값
print(arr2)

[[0.05086951 1.72759674 1.29022981]
 [1.10096879 0.55379542 0.47442663]
 [0.51919113 0.39620118 0.8097372 ]]


In [126]:
np.isnan(arr1) # nan이 있나요? 있으면 트루

array([[ True,  True, False],
       [False,  True, False],
       [ True,  True,  True]])